name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب المشروع من جيت هاب
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. تهيئة لغة جافا الضرورية لبناء الأندرويد
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تهيئة بيئة فلاتر المستقرة
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # إصدار مستقر ومتوافق مع مكتباتك
          channel: 'stable'

      # 4. تنظيف الكاش والملفات المؤقتة تماماً لمنع تكرار الأخطاء القديمة
      - name: Clean Project Cache
        run: flutter clean

   # 5. جلب المكتبات والإصدارات الصحيحة
      - name: Install Dependencies
        run: flutter pub get

      # الخطوة السحرية لإصلاح ملفات Gradle القديمة تلقائياً
     

      # 6. بناء ملف الـ APK النهائي بنجاح
      - name: Build Comprehensive APK
        run: flutter build apk --debug

      # 7. رفع ملف الـ APK الناتج لكي تتمكن من تحميله من صفحة الـ Actions
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: quran-prayer-app-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
