name: Flutter Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Full Flutter Project Structure
        run: |
          # حفظ كود الواجهة والملفات الأساسية مؤقتاً
          mv lib/main.dart ./temp_main.dart
          mv pubspec.yaml ./temp_pubspec.yaml
          
          # إعادة إنشاء هيكل المشروع بالكامل وبشكل رسمي
          rm -rf ./* ./.* 2>/dev/null || true
          flutter create --org com.ewais.ward quran_ward_app .
          
          # استعادة الأكواد الفاخرة الخاصة بك مكان الملفات الافتراضية
          rm -f pubspec.yaml lib/main.dart
          mv ./temp_main.dart lib/main.dart
          mv ./temp_pubspec.yaml pubspec.yaml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
